version: 2.1

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"
  project-git_url:
    type: string
    default: ""
  git-base_revision:
    type: string
    default: ""
  git-revision:
    type: string
    default: ""

orbs:
  orb-tools: circleci/orb-tools@9.0.1
  dscar: moneyforward/dscar@<< pipeline.parameters.dev-orb-version >>

anchors:
  dscar-default-executor: &dscar-default-executor
    name: dscar/default
    project-git_url: << pipeline.parameters.project-git_url >>
    git-base_revision: << pipeline.parameters.git-base_revision >>
    git-revision: << pipeline.parameters.git-revision >>

jobs:
  integration-test-1:
    executor:
      <<: *dscar-default-executor
    steps:
      - checkout
      - dscar/analyze
  integration-test-2:
    executor:
      <<: *dscar-default-executor
    steps:
      - run:
          name: setup
          command: |
            declare -x CIRCLE_PULL_REQUEST=https://github.com/moneyforward/dscar/pull/6
            declare -x CIRCLE_PULL_REQUESTS=$CIRCLE_PULL_REQUEST
            declare -x CIRCLE_USERNAME=naokikimura
            declare -x CIRCLE_SHA1=0a25943dce63cb2ac481dd8b672bfe53384f8086

            ANALYSIS_NAME=CoffeeLint
            BASE_SHA=5e563b0a2f9dd712a285a7835797afded818f79b
            HEAD_SHA=$CIRCLE_SHA1
            declare -Ax DSCAR_COMMIT_RANGES=(
              ["${CIRCLE_PULL_REQUEST}"]="${BASE_SHA}..${HEAD_SHA}"
            )

            mkdir -p "${DSCAR_ANALYSIS_RESULTS_PATH}/${ANALYSIS_NAME}"
            cat \<<-EOT > ${DSCAR_ANALYSIS_RESULTS_PATH}/${ANALYSIS_NAME}/${HEAD_SHA}-analysis-result.xml
            <?xml version="1.0" encoding="UTF-8"?>
            <checkstyle>
              <file name="app/assets/javascripts/index.js.coffee">
                <error source="no_unnecessary_double_quotes" message="Unnecessary double quotes are forbidden" severity="error" line="1" column="0"/>
                <error source="no_unnecessary_double_quotes" message="Unnecessary double quotes are forbidden" severity="error" line="1" column="0"/>
                <error source="no_unnecessary_double_quotes" message="Unnecessary double quotes are forbidden" severity="error" line="3" column="0"/>
                <error source="no_unnecessary_double_quotes" message="Unnecessary double quotes are forbidden" severity="error" line="4" column="0"/>
                <error source="no_unnecessary_double_quotes" message="Unnecessary double quotes are forbidden" severity="error" line="4" column="0"/>
                <error source="no_unnecessary_double_quotes" message="Unnecessary double quotes are forbidden" severity="error" line="6" column="0"/>
                <error source="no_unnecessary_double_quotes" message="Unnecessary double quotes are forbidden" severity="error" line="7" column="0"/>
              </file>
            </checkstyle>
            EOT

            cat \<<-EOT >> $BASH_ENV
            $(declare -p CIRCLE_SHA1)
            $(declare -p CIRCLE_USERNAME)
            $(declare -p CIRCLE_PULL_REQUEST)
            $(declare -p CIRCLE_PULL_REQUESTS)
            $(declare -p DSCAR_COMMIT_RANGES)
            EOT

            COMMENT_FINGERPRINTS_PATH="/tmp/dscar/comment-fingerprints/.MESSAGES_THAT_COULD_NOT_BE_COMMENTED"
            COMMENT_FINGERPRINTS="${COMMENT_FINGERPRINTS_PATH}/$(echo "${CIRCLE_PULL_REQUEST}" | sha1sum | cut -c1-40)"
            mkdir -p "$(dirname "${COMMENT_FINGERPRINTS}")"
            echo '172a6b294407e6b80b2f6bb270e951c7c19960a9  -' > "${COMMENT_FINGERPRINTS}"
      - dscar/comment:
          when: on_success
  integration-test-6:
    executor:
      <<: *dscar-default-executor
    steps:
      - checkout
      - run:
          name: setup
          command: |
            git remote update
            BASE=$(git rev-parse v1.0.0)
            HEAD=$(git rev-parse v1.0.2)
            RESULT_PATH="${DSCAR_ANALYSIS_RESULTS_PATH}/true/0/${HEAD}-analysis-result.xml"
            mkdir -p "$(dirname "${RESULT_PATH}")"
            cat \<<-EOT > "$RESULT_PATH"
            <checkstyle>
              <file name="${PWD}/src/commands/analyze.yml">
                <error source="foo" message="hello" line="115" column="0" severity="error" />
                <error source="bar" message="world" line="116" column="0" severity="error" />
                <error source="baz" message="abcde" line="114" column="0" severity="error" />
              </file>
            </checkstyle>
            EOT
            declare -Ax DSCAR_COMMIT_RANGES=( [0]="${BASE}..${HEAD}" )
            echo "$(declare -p DSCAR_COMMIT_RANGES)" >> $BASH_ENV
      - dscar/refine-analysis-result
      - run:
          name: evaluate
          command: |
            set -x
            DELTA=b6589fc6ab0dc82cf12099d1c2d40ab994e8410c
            RESULT_PATH="${DSCAR_ANALYSIS_RESULTS_PATH}/true/0/${DELTA}-DELTA-analysis-result.xml"
            test -e "$RESULT_PATH"
            sudo apt-get install xmlstarlet
            test $(xmlstarlet sel -t -m '//error' -n < "$RESULT_PATH" | wc -l) -eq 1
            xmlstarlet sel -t -m "//file[@name='${PWD}/src/commands/analyze.yml']/error[@line='115']" -c '.' -n < "$RESULT_PATH"

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          context: dscar
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          context: dscar
          orb-name: moneyforward/dscar
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          context: dscar
          name: trigger-integration-dev
          pipeline-param-map: |
            {
              \"run-integration-tests\": true,
              \"dev-orb-version\": \"dev:${CIRCLE_SHA1:0:7}\",
              \"project-git_url\": \"<< pipeline.project.git_url >>\",
              \"git-base_revision\": \"<< pipeline.git.base_revision >>\",
              \"git-revision\": \"<< pipeline.git.revision >>\"
            }
          requires:
            - orb-tools/publish-dev
    unless: << pipeline.parameters.run-integration-tests >>
  integration-tests:
    jobs:
      - integration-test-1
      - integration-test-2
      - integration-test-6
    when: << pipeline.parameters.run-integration-tests >>
